"""
Regenerate js/tles.js - the element sets the site's sky plot propagates.

The list of satellites is the ground station's own watch list, read from
SatelliteDashboard/config.py. Element sets come from the dashboard's disk
cache by default; pass --fetch to pull fresh ones from CelesTrak instead.

    python tools/build_tles.py            # from the dashboard cache
    python tools/build_tles.py --fetch    # from CelesTrak (needs internet)

Run it before each deploy. The page also refreshes stale sets from
CelesTrak on its own, but a fresh bundle means nobody has to wait for that.
"""
import json
import re
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DASHBOARD = ROOT.parent / "SatelliteDashboard"
OUT = ROOT / "js" / "tles.js"


def watchlist():
    src = (DASHBOARD / "config.py").read_text(encoding="utf-8")
    block = src[src.index("WATCHLIST = ["):]
    block = block[: block.index("]\n")]
    return [(int(n), name) for n, name in re.findall(r'\((\d+),\s*"([^"]+)"\)', block)]


def from_cache(norad):
    path = DASHBOARD / "cache" / f"tle_{norad}.json"
    if not path.exists():
        return None
    rows = json.loads(path.read_text(encoding="utf-8"))
    if not rows:
        return None
    return rows[0]["tle1"].strip(), rows[0]["tle2"].strip()


def from_celestrak(norad):
    url = f"https://celestrak.org/NORAD/elements/gp.php?CATNR={norad}&FORMAT=TLE"
    with urllib.request.urlopen(url, timeout=20) as r:
        lines = [l.strip() for l in r.read().decode().splitlines() if l.strip()]
    return (lines[1], lines[2]) if len(lines) >= 3 else None


def main():
    fetch = "--fetch" in sys.argv
    sats, skipped = [], []
    for norad, name in watchlist():
        tle = from_celestrak(norad) if fetch else from_cache(norad)
        if tle:
            sats.append({"norad": norad, "name": name, "l1": tle[0], "l2": tle[1]})
        else:
            skipped.append(name)

    payload = {
        "built": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%MZ"),
        "source": "CelesTrak" if fetch else "station cache (SatNOGS / Space-Track)",
        "sats": sats,
    }
    OUT.write_text(
        "// Generated by tools/build_tles.py - do not edit by hand.\n"
        "window.STATION_TLES = " + json.dumps(payload, indent=1) + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {len(sats)} element sets to {OUT}")
    if skipped:
        print("no element set (re-entered, geostationary-only, or missing):", ", ".join(skipped))


if __name__ == "__main__":
    main()
